version: '3'

services:
  php:
    container_name: php
    build: ./services/php
    volumes:
    - ./dawn:/usr/share/nginx/dawn

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./dawn:/usr/share/nginx/dawn
    - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #depends_on:
    #- php

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./services/db/data:/var/lib/mysql
    - ./services/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./services/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
